Repository Adventure-Club-mob/Website, pull requests merged in 2021-06, with the labels that each got.

#14 Home page , Mobile view responsive animation and image resize were almost done
  css/main.css
  css/responsive.css
  images/home/elizian-.png
  images/home/elizian.png
  images/home/red-bull.png
  images/png/adventurer.png
  images/png/camp.png
  images/png/camping.png
  images/png/explore.png
  images/png/guide.jpg
  images/png/guide.png
  images/png/skill.png
  index.html
Labels: bug, help wanted

#19 Mob-Responsive, About us & History pages, Team members(whole team) are added/changed...
  aboutus.html
  contact.html
  contact2.html
  css/main.css
  css/responsive.css
  history.html
  images/aboutus/1.jpg
  images/aboutus/2.jpg
  images/aboutus/3.jpg
  images/aboutus/about.jpeg
  images/aboutus/history.jpeg
  images/home/Bear-Grylls.jpg
  images/home/eleanor-roosevelt.jpg
  images/home/footer-1.png
  images/home/helen.jpg
  images/home/image4.png
  images/home/joshgates.jpg
  images/home/obama.png
  images/team/4.jpg
  images/team/Assistant_Secretary_Githmi.png
  images/team/Discoverer_Priyankara.png
  images/team/Faculty_of_Commerce&Management_Kasun.png
  images/team/Faculty_of_Computing&Technology_Bhawanthani.png
  images/team/Faculty_of_Humanities_Nemindi.png
  images/team/Faculty_of_Medicine_Theekshana.png
  images/team/Faculty_of_Science_Dulanjana.png
  images/team/Faculty_of_SocialSciences_Saliya.png
  images/team/Head_of_the_Junior_Committee_Members_Lalindra.png
  images/team/Junior_Treasurer_Singhe.jpg
  images/team/Medic_Induru.png
  images/team/Osura-Faculty_of-Science.png
  images/team/Pathmika-Faculty_of_Science.png
  images/team/President_Lilan.png
  images/team/Public_Sector_Coordinator_Nabeel.jpg
  images/team/Secretary_Erandi.png
  images/team/Special_Task_Organizer_Chandeepa.png
  images/team/Special_Task_Organizer_Pasindi.png
  images/team/Vice_President_Ishara.png
  images/team/Webmaster_Pankajan.png
  index.html
Labels: bug, documentation, enhancement

#25 add the message sending and show it in the home page
  css/main.css
  index.html
  js/sendmail.js
Labels: bug, enhancement

#27 I have finished the major problems,,
  aboutus.html
  contact.html
  css/main.css
  css/responsive.css
  game.html
  history.html
  images/games/ac-kln-1-25%.png.tmp$$
  images/games/ac-kln-2-35%.png.tmp$$
  images/games/ac-kln-design.png.tmp$$
  images/games/ac-kln-right.png.tmp$$
  images/games/ac-kln-rm-bg.jpg
  images/games/ac-kln-rm-bg.png.tmp$$
  index.html
  js/sendmail.js
Labels: bug, enhancement

#29 Devlopment
  game.html
  game1.html
  game2.html
  images/games/menja.jpg
Labels: enhancement
